64378890-01:
  "KRW":
    "threshold": 0.08  # KRW는 8% threshold
    "assets":
      "379800": 0.29  # kodex s&p 500
      "379810": 0.29  # kodex 나스닥 100
      "305080": 0.10  # tiger 미국채 10년
      "468630": 0.10  # kodex 미국 회사채
      "469830": 0.10  # sol 초단기채권
      "411060": 0.10  # ace krx 금 현물
  "USD":
    "threshold": 0.08  # USD는 10% threshold
    "assets":
      "TSLL": 0.05
      "TSLY": 0.05
      "PLTR": 0.20
      "TSLY": 0.25
      "SHY": 0.10
      "IEF": 0.10
      "TLT": 0.10
      "IAU": 0.15
64521213-01:
  "KRW":
    "threshold": 0.08  # 이 계좌는 8% threshold
    "assets":
      "379800": 0.29  # kodex s&p 500
      "379810": 0.29  # kodex 나스닥 100
      "305080": 0.10  # tiger 미국채 10년
      "468630": 0.10  # kodex 회사채
      "469830": 0.10  # sol 초단기채권
      "411060": 0.10  # ace krx 금 현물
